name: CI

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  danger-outside:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'ok to danger') && github.repository != 'nomifactory-ja/nomifactory-ja'

    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID_DANGERBOT }}
          private_key: ${{ secrets.APP_PEM_DANGERBOT }}

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: "Download NPM packages"
        run: npm ci

      - name: "Danger"
        run: npx danger ci
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

  danger:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.repository == 'nomifactory-ja/nomifactory-ja'

    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID_DANGERBOT }}
          private_key: ${{ secrets.APP_PEM_DANGERBOT }}

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: "Download NPM packages"
        run: npm ci

      - name: "Danger"
        run: npx danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
